### ISSUE TITLE
Use in Unity C# environment?

### ISSUE THREAD

**Issue by jonnyijapan** [kinetiq/Ether.WeightedSelector#1]
I couldn't use this out-of-the-box in a C# Unity environment. I'm sorry, I don't even know what a Nuget it. But I just wanted to use this class but turns out it complained about not knowing what System.Task is etc and I just gave up there.

**Comment by jonnyijapan** [comment]
Sorry for being busy with other things. I'll likely need something like this in coming projects again and will likely take a look at it sometime ahead. 


2014/12/18 22:29$B!"(BBrian MacKay <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by kinetiq** [comment]
Ah, great. I'm pretty sure I need to rebuilt this as a portable class library project, which wouldn't be hard, but I do need someone to confirm that it works on unusual platforms for me. Let me know when you're up for testing and I will make the change.
